### ISSUE TITLE
scan: no attribute 'has_key'

### ISSUE THREAD

**Issue by ekkis** [tuladhar/wifi-manager#7]
```
# wifi-cli scan
```
produces:

> Traceback (most recent call last):
>   File "/Users/ekkis/.local/bin/wifi-cli", line 362, in <module>
>     sys.exit(main())
>   File "/Users/ekkis/.local/bin/wifi-cli", line 341, in main
>     if cmd.has_key('arguments'):
> AttributeError: 'dict' object has no attribute 'has_key'

**Comment by ekkis** [comment]
here's the solution: https://www.perplexity.ai/search/attributeerror-dict-object-has-9kCySbDmRbipjMujdC3r_g
