### ISSUE TITLE
object not subscriptable

### ISSUE THREAD

**Issue by ekkis** [tuladhar/wifi-manager#8]
```
# wifi-cli scan
```
produces:

> Traceback (most recent call last):
>   File "/Users/ekkis/.local/bin/wifi-cli", line 362, in <module>
>     sys.exit(main())
>   File "/Users/ekkis/.local/bin/wifi-cli", line 356, in main
>     wifi = WiFi(args.interface)
>   File "/Users/ekkis/.local/bin/wifi-cli", line 180, in __init__
>     self.interface = WiFi.auto_detect()
>   File "/Users/ekkis/.local/bin/wifi-cli", line 169, in auto_detect
>     next_line = lines[no+1]
> TypeError: 'filter' object is not subscriptable

**Comment by ekkis** [comment]
so this owes to the fact that `lines` is the result of a filter and needs to be converted to an array before it can be subscripted.  however, when I fix that I get the error:

> WARNING: The airport command line tool is deprecated and will be removed in a future release.
> For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool

WTF?
